%%designingstruct
members=struct('name',{},'age',{},'course',{},'district',{},'tribe',{},'village',{},'religion',{},'interest',{},'facialrepresentation',{});
%member(1)
members(1).name='gift_emmanuel';
members(1).age='20';
members(1).course='war';
members(1).district='koboko';
members(1).tribe='kakwa';
members(1).village='keri';
members(1).religion='anglican';
members(1).interest='prayers';
members(1).facialrepresentation=imread('ngc6543a.jpg');
%members(2)
members(2).name='ahaisibwe_christopher';
members(2).age='22';
members(2).course='ami';
members(2).district='wakiso';
members(2).tribe='munyankole';
members(2).village='bujjuuko';
members(2).religion='catholic';
members(2).interest='swimming';
members(2).facialrepresentation=imread('ngc6543a.jpg');
%members(3)
members(3).name='arach_gladys';
members(3).age='21';
members(3).course='war';
members(3).district='gulu';
members(3).tribe='acholi';
members(2).religion='catholic';
members(3).village='bardege';
members(3).interest='music';
members(3).facialrepresentation=imread('ngc6543a.jpg');

%members(4)
members(4).name='adwong_caled';
members(4).age='22';
members(4).course='meb';
members(4).district='tororo';
members(4).tribe='japadhola';
members(4).religion='born_again';
members(4).village='paya';
members(4).interest='basketball';
members(4).facialrepresentation=imread('ngc6543a.jpg');

%members(5)
members(5).name='rose_miriam';
members(5).age='22';
members(5).course='war';
members(5).district='trinyi';
members(5).tribe='bugwere';
members(5).religion='pentacostal';
members(5).village='kibuku';
members(5).interest='dancing';
members(5).facialrepresentation=imread('ngc6543a.jpg');

%members(6)
members(6).name='posh';
members(6).age='23';
members(6).course='war';
members(6).district='tororo';
members(6).tribe='japadhola';
members(6).religion='catholic';
members(6).village='kisoko';
members(6).interest='gaming';
members(6).facialrepresentation=imread('ngc6543a.jpg');

%members(7)
members(7).name='amaso_susan';
members(7).age='23';
members(7).course='pti';
members(7).district='amuria';
members(7).tribe='iteso';
members(7).religion='catholic';
members(7).village='odekere';
members(7).interest='learning';
members(7).facialrepresentation=imread('ngc6543a.jpg');

%members(8)
members(8).name='opoka_vincent';
members(8).age='22';
members(8).course='ami';
members(8).district='lamwo';
members(8).tribe='acholi';
members(8).religion='catholic';
members(8).village='lugu';
members(8).interest='football';
members(8).facialrepresentation=imread('ngc6543a.jpg');

%members(9)
members(9).name='ahereza_faith';
members(9).age='22';
members(9).course='ape';
members(9).district='isingiro';
members(9).tribe='munyankole';
members(9).religion='anglican';
members(9).village='watching';
members(9).interest='music';
members(9).facialrepresentation=imread('ngc6543a.jpg');

%members(10)
members(10).name='wangusi_david';
members(10).age='21';
members(10).course='meb';
members(10).district='busia';
members(10).tribe='samia';
members(10).religion='catholic';
members(10).village='mayombe';
members(10).interest='football';
members(10).facialrepresentation=imread('ngc6543a.jpg');

%members(11)
members(11).name='twale_joshua';
members(11).age='2';
members(11).course='ape';
members(11).district='mbale';
members(11).tribe='gishu';
members(11).religion='catholic';
members(11).village='namakwekwe';
members(11).interest='football';
members(11).facialrepresentation=imread('ngc6543a.jpg');

%members(12)
members(12).name='acipa_bridget';
members(12).age='21';
members(12).course='war';
members(12).district='lira';
members(12).tribe='langi';
members(12).religion='catholic';
members(12).village='bardege';
members(12).interest='music';
members(12).facialrepresentation=imread('ngc6543a.jpg');

%members(13)
members(13).name='oule_saddock';
members(13).age='22';
members(13).course='meb';
members(13).district='busia';
members(13).tribe='samia';
members(13).religion='catholic';
members(13).village='bukedi';
members(13).interest='travelling';
members(13).facialrepresentation=imread('ngc6543a.jpg');

%members(14)
members(14).name='nabukeera_annet_rhionah';
members(14).age='21';
members(14).course='ami';
members(14).district='jinja';
members(14).tribe='musoga';
members(14).religion='catholic';
members(14).village='town';
members(14).interest='reading';
members(14).facialrepresentation=imread('ngc6543a.jpg');

%members(15)
members(15).name='muwubya_wycliffe';
members(15).age='23';
members(15).course='war';
members(15).district='kampala';
members(15).tribe='mugandan';
members(15).religion='born_again';
members(15).village='busega';
members(15).interest='prayers';
members(15).facialrepresentation=imread('ngc6543a.jpg');

%members(16)
members(16).name='akello_barbra';
members(16).age='22';
members(16).course='war';
members(16).district='busia';
members(16).tribe='samia';
members(16).religion='catholic';
members(16).village='shaule';
members(16).interest='business';
members(16).facialrepresentation=imread('ngc6543a.jpg');

%members(17)
members(17).name='atati_edwine';
members(17).age='25';
members(17).course='ami';
members(17).district='maracha';
members(17).tribe='lugbara';
members(17).religion='anglican';
members(17).village='nyandi';
members(17).interest='gym';
members(17).facialrepresentation=imread('ngc6543a.jpg');

%members(18)
members(18).name='ocaa_eli';
members(18).age='21';
members(18).course='war';
members(18).district='lira';
members(18).tribe='langi';
members(18).religion='catholic';
members(18).village='town';
members(18).interest='singimg';
members(18).facialrepresentation=imread('ngc6543a.jpg');

%members(19)
members(19).name='awene_solomon';
members(19).age='24';
members(19).course='war';
members(19).district='lira';
members(19).tribe='langi';
members(19).religion='catholic';
members(19).village='bardege';
members(19).interest='riding';
members(19).facialrepresentation=imread('ngc6543a.jpg');

%members(20)
members(20).name='buluma_daniel';
members(20).age='23';
members(20).course='ami';
members(20).district='busia';
members(20).tribe='samia';
members(20).religion='anglican';
members(20).village='nyandi';
members(20).interest='readin';
members(20).facialrepresentation=imread('ngc6543a.jpg');